accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('register/', views.RegistrationView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('activate/<uidb64>/<token>/', views.ActivateView.as_view(), name='activate'),
    path('forgotPassword/', views.ForgotPasswordView.as_view(), name='forgotPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', views.ResetPasswordValidateView.as_view(), name='resetpassword_validate'),
    path('resetPassword/', views.ResetPasswordView.as_view(), name='resetPassword'),

    path('profile/', views.EditProfileView.as_view(), name='edit_profile'),
    path('change_password/', views.ChangePasswordView.as_view(), name='change_password'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('accounts.urls')),
    path("fantasy/", include('fantasy.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from .models import Account, UserProfile
from django.core.validators import MinLengthValidator



class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
        'class': 'form-control',
    }),
        validators=[MinLengthValidator(limit_value=6, message="Password must be at least 6 characters.")]
    )
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password'
    }),
        validators=[MinLengthValidator(limit_value=6, message="Password must be at least 6 characters.")]
    )

   
    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'phone_number', 'email', 'password']

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        phone_number=cleaned_data.get('phone_number')

        if password != confirm_password:
            raise forms.ValidationError(
                "Password does not match!"
            )
        if  len(phone_number) != 10:
            raise forms.ValidationError(
                " Number of digit in Phone Number should be 10 "
            )
            
        if not phone_number.isdigit() or len(phone_number) != 10:
            raise forms.ValidationError(
                "Enter Valid Phone Number "
            )
        

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter First Name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter last Name'
        self.fields['phone_number'].widget.attrs['placeholder'] = 'Enter Phone Number'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter Email Address'
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class UserForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('first_name', 'last_name', 'phone_number')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'



class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False, error_messages = {'invalid':("Image files only")}, widget=forms.FileInput)
    full_name = forms.CharField(max_length=250, required=False)
    email = forms.EmailField(required=False)
    class Meta:
        model = UserProfile
        fields = ('profile_picture' ,)

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    def save(self, commit=True):
        instance = super().save(commit=False)
        
        full_name = self.cleaned_data.get('full_name', '').split(' ')
        instance.user.first_name = full_name[0] if full_name else ''
        instance.user.last_name = full_name[1] if len(full_name) > 1 else ''

        instance.user.email = self.cleaned_data.get('email', '')

        if commit:
            instance.user.save()  
            instance.save()  


        return instance

accounts/views.py
from typing import Any
from django.views import View
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.core.mail import EmailMessage
from django.shortcuts import render, redirect
from .forms import RegistrationForm
from .models import Account
import requests
from .forms import *
from django.views.generic.base import TemplateView
from fantasy.models import Article

from core.mixins import CustomLoginRequiredMixin


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['articles'] = Article.objects.all()[:3] if Article.objects.exists() else None
        return context

class AboutView(TemplateView):
    template_name = 'about.html'


# Registration View
class RegistrationView(View):
    def get(self, request):
        form = RegistrationForm()
        context = {'form': form}
        return render(request, 'accounts/register.html', context)

    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            phone_number = form.cleaned_data['phone_number']
            password = form.cleaned_data['password']
            username = email.split('@')[0]
            if Account.objects.filter(username=email.split('@')[0]):
                messages.error(request, 'A user with given email already exists. Please try with new email or recover your old one.')
                context = {'form': form}
                return render(request, 'accounts/register.html', context)
            user = Account.objects.create_user(first_name=first_name, last_name=last_name, email=email, username=username, password=password)
            user.phone_number = phone_number
            user.save()

            # user_activation
            current_site = get_current_site(request)
            mail_subject = 'Please activate your account'
            message = render_to_string('accounts/account_verification_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()
            return redirect('/login/?command=verification&email=' + email)

        context = {'form': form}
        return render(request, 'accounts/register.html', context)

# Login View
class LoginView(View):
    def get(self, request):
        return render(request, 'accounts/login.html')

    def post(self, request):
        email = request.POST['email']
        password = request.POST['password']
        user = auth.authenticate(email=email, password=password)

        if user is not None:

            auth.login(request, user)
            messages.success(request, 'You are now logged in.')
            url = request.META.get('HTTP_REFERER')
            try:
                query = requests.utils.urlparse(url).query
                params = dict(x.split('=') for x in query.split('&'))
                if 'next' in params:
                    nextPage = params['next']
                    return redirect(nextPage)
            except:
                return redirect('accounts:edit_profile')
        else:
            messages.error(request, 'Invalid login credentials')
        return render(request, 'accounts/login.html')

# Logout View
class LogoutView(View, CustomLoginRequiredMixin):
    def get(self, request):
        auth.logout(request)
        messages.success(request, "You are now logged out!")
        return redirect('accounts:login')

# Activation View
class ActivateView(View):
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = Account._default_manager.get(pk=uid)
        except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(request, 'Congratulations! Your account is now activated.')
            return redirect('accounts:login')
        else:
            messages.error(request, 'Invalid activation link')
            return redirect('accounts:register')


# Forgot Password View
class ForgotPasswordView(View):
    def get(self, request):
        return render(request, 'accounts/forgotPassword.html')

    def post(self, request):
        email = request.POST['email']
        if Account.objects.filter(email=email).exists():
            user = Account.objects.get(email__exact=email)

            # Reset password email
            current_site = get_current_site(request)
            mail_subject = 'Please reset your password'
            message = render_to_string('accounts/reset_password_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()

            messages.success(request, 'Password reset email has been sent to your email address.')
            return redirect('accounts:login')
        else:
            messages.error(request, 'Account does not exist!')
            return redirect('accounts:forgotPassword')

# Reset Password Validation View
class ResetPasswordValidateView(View):
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = Account._default_manager.get(pk=uid)
        except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            request.session['uid'] = uid
            messages.success(request, 'Please reset your password')
            return redirect('accounts:resetPassword')
        else:
            messages.error(request, 'This link has expired!')
            return redirect('accounts:login')

# Reset Password View
class ResetPasswordView(View):
    def get(self, request):
        return render(request, 'accounts/resetPassword.html')

    def post(self, request):
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            uid = request.session.get('uid')
            user = Account.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request, 'Password reset successful!')
            return redirect('accounts:login')
        else:
            messages.error(request, 'Passwords do not match')
            return redirect('accounts:resetPassword')

# Edit Profile View
class EditProfileView(CustomLoginRequiredMixin, View):
    def get(self, request):
        user_form = UserProfileForm(instance=request.user)
        try:
            current_profile = UserProfile.objects.get(user=request.user)
        except Exception as e:
            current_profile = UserProfile.objects.create(user=request.user)
            pass
        context = {'user_form': user_form, 'current_profile': current_profile, 'curr_nav': 'profile'}
        return render(request, 'accounts/edit_profile.html', context=context)

    def post(self, request):
        try:
            user_profile = UserProfile.objects.get(user=request.user)
        except UserProfile.DoesNotExist:
            user_profile = UserProfile.objects.create(
                user=request.user
            )
    
        user_form = UserProfileForm(request.POST, request.FILES, instance=user_profile)
        if user_form.is_valid():
            user_form.save()

            new_password = request.POST['password']
            confirm_password = request.POST['confirm_password']
            user = self.request.user
            if new_password and confirm_password:
                if new_password == confirm_password:
                    user.set_password(new_password)
                    user.save()
                else:
                    messages.error(request, 'Two passwords do not match.')
                    return redirect('edit_profile')
            messages.success(request, 'Your Profile Has Been Updated')
            return redirect('accounts:edit_profile')
        else:
            print('form is not valid...')
            print(user_form.errors)
            
            return redirect('accounts:edit_profile')

# Change Password View
class ChangePasswordView(View, CustomLoginRequiredMixin):
    def get(self, request):
        return render(request, 'accounts/change_password.html')

    def post(self, request):
        current_password = request.POST['current_password']
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']

        user = Account.objects.get(username__exact=request.user.username)

        if new_password == confirm_password:
            success = user.check_password(current_password)
            if success:
                user.set_password(new_password)
                user.save()

templates/accounts/account_verification_email.html
{% autoescape off %}
Hi {{user.first_name}},
Please click link below to confirm your registation at Fantasy Team.
http://{{domain}}{% url 'accounts:activate' uidb64=uid token=token %}

If you think this is not you. Please ignore this email.
{% endautoescape %}

templates/accounts/change_password.html
{% extends 'layouts/base.html' %}

{% block content %}

<br><br><br>
<section class="section-conten padding-y bg align-items-center">
    {% include 'includes/alerts.html' %}
    <div class="container">
        <div class="row">
        {% include 'includes/dashboard_sidebar.html' %}
       
        <main class="col-md-9">
            <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3">Change Password</strong>
            </header>
            <div class="card-body">

                <div class="row"> 

                <div class="col-md-12"> 
                <form action="{% url 'accounts:change_password' %}" method="POST" enctype="multipart/form-data">
                  {% csrf_token %}

                  <div class="form-group">
                  <label>Current Password</label>
                   <input type="password" name="current_password" placeholder="current password" class="form-control" required>
                  </div>
                   <div class="form-group">
                  <label> Create new password </label>
                 <input type="password" name="new_password" placeholder="Create new password" class="form-control" required>
                  </div>

                  <div class="form-group">
                  <label> Confirm new password </label>
                 <input type="password" name="confirm_password" placeholder="Confirm new password" class="form-control" required>
                  </div>

                  <input type="submit" value="Submit" class="btn btn-primary"> 

                </form>

                </div>
                     
                </div> <!-- row.// -->
            </div> <!-- card-body .// -->

            </article> <!-- order-group.// --> 
        </main>
    </div> <!-- row.// -->
    </div>
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    

{% endblock %}

templates/accounts/dashboard.html
{% extends 'layouts/base.html' %}


{% block content %}

<section class="section-conten padding-y bg">

{% include 'includes/alerts.html' %}
<div class="container">
	<div class="row">
	{% include 'includes/dashboard_sidebar.html' %}
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Logged in as:</strong>
			<span>{{user.full_name}}</span>
		</header>
		<div class="card-body">
			<div class="row">

			<div class="col-md-6">
				<div class="card" style="text-align:center;">
					<div class="card-body">

					</div>
				</div>
			</div>
			<div class="col-md-6">
				<div class="card" style="text-align:center;">
					<div class="card-body">
						<object data="https://romanroadtrust.co.uk/wp-content/uploads/2018/01/profile-icon-png-898-300x300.png" width="50" height="50"  type="image/png">
						<img src="{{userprofile.profile_picture.url}}" alt="User Profile Picture" width="50" height="50" style="border-radius:50%;">
					</object>
						<p class="mb-0">{{user.email}}</p>
						<p>{{user.phone_number}}</p>
					</div>
				</div>
			</div>

			</div> <!-- row.// -->
		</div> <!-- card-body .// -->

		</article> <!-- order-group.// -->
	</main>
</div> <!-- row.// -->
</div>


</section>

{% endblock %}

templates/accounts/edit_profile.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block content %}
<!-- Main Content -->
<div class="main-content pt-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <form action="{% url 'accounts:edit_profile' %}" method="post" enctype="multipart/form-data" class="card">
                    {% csrf_token %}
                    <div class="card-header">
                        <h4>Edit Profile</h4>
                    </div>
                    <div class="card-body">

                        <!-- Profile Picture -->
                        <div class="form-group text-center">
                            <img src="{{ current_profile.title_photo }}" alt="" class="profile-avatar img-fluid rounded-circle mb-3" style="width: 150px; height: 150px;">
                            <input type="file" name="profile_picture" id="profileFile" hidden>
                            <button type="button" class="btn btn-outline-secondary change-profile">Change Picture</button>
                        </div>

                        <!-- Full Name -->
                        <div class="form-group">
                            <label for="fullName">Full Name</label>
                            <input type="text" class="form-control" id="fullName" name="full_name" placeholder="Full Name" value="{{ current_profile.full_name }}">
                        </div>

                        <!-- Email -->
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="email" name="email" placeholder="Type your email" value="{{ current_profile.get_email }}">
                        </div>

                        <!-- Password -->
                        <h5 class="mt-4">Change Password</h5>
                        <div class="form-group">
                            <label for="password">New Password</label>
                            <input type="password" class="form-control" id="password" name="password" placeholder="Enter new password">
                        </div>

                        <div class="form-group">
                            <label for="confirmPassword">Confirm New Password</label>
                            <input type="password" class="form-control" id="confirmPassword" name="confirm_password" placeholder="Enter new password again">
                        </div>

                    </div>
                    <div class="card-footer text-right">
                        <button type="submit" class="btn btn-primary">Save Changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- End Main Content -->
{% endblock content %}

{% block script %}
<script>
    $(document).ready(function () {
        // Profile picture change
        $('.change-profile').click(function () {
            $('#profileFile').click();
        });

        $('#profileFile').change(function (e) {
            const file = e.target.files[0];
            if (file) {
                const reader = new FileReader();
                reader.onload = function (e) {
                    $('.profile-avatar').attr('src', e.target.result);
                };
                reader.readAsDataURL(file);
            }
        });
    });
</script>
{% endblock script %}

templates/accounts/forgotPassword.html
{% extends 'layouts/base.html' %}

{% block content %}

<div class="min-vh-100 d-flex align-items-center">
    <div class="container">
        
        <div class="row justify-content-center">
            <div class="col-xl-9">
                <!-- Card -->
               


                <div class="card auth-card">
                    <div class="row justify-content-center">
                        <div class="col-xl-8 col-lg-10">
                            <h4 class="mb-5 font-20">Forget Password</h4>

                            <form action="{% url 'accounts:forgotPassword' %}" method="post">
                                {% csrf_token %}
                                
                                <!-- Form Group -->
                                <div class="form-group mb-4">
                                    <label for="email" class="mb-2 font-14 bold black">Email Address</label>
                                    <input required type="email" name="email" class="theme-input-style" placeholder="Email Address">
                                </div>
                                <!-- End Form Group -->

                                <button type="submit" class="btn btn-primary btn-long">Reset Password</button>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- End Card -->
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/accounts/forgotPassword2.html
{% extends 'layouts/base.html' %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->

        <div class="card mx-auto" style="max-width: 600px; margin-top:100px;">
            
          <div class="card-body">
          <h4 class="card-title mb-4">Forgot Password</h4>
          {% include 'includes/alerts.html' %}
          <form action="{% url 'accounts:forgotPassword' %}" method="POST">
              {% csrf_token %}
              <div class="form-group">
                 <input required type="email" class="form-control" placeholder="Email Address" name="email" >
              </div> <!-- form-group// -->
              
              <div class="form-group">
                  <a href="{% url 'accounts:login' %}" class="float-right">Got password? Login</a> 
               
              </div> <!-- form-group form-check .// -->
              <div class="form-group">
                  <button type="submit" class="btn btn-primary btn-block"> Submit  </button>
              </div> <!-- form-group// -->    
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
         <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
         <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->

    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/login.html
{% extends 'layouts/base.html' %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->
    {% if request.GET.command == 'verification' %}

    <div class="container mx-auto alert alert-info text-center" role="alert" style="max-width: 1024px; margin-top:100px;">
    Thank you for registering with us. We have sent you a verification email to your email address [{{ request.GET.email }}]
    <br><br>
    Already verified? <a href="{% url 'accounts:login' %}">Login</a>
    </div>
    
    {% else %}

        <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
            
          <div class="card-body">
          <h4 class="card-title mb-4">Sign in</h4>
          {% include 'includes/alerts.html' %}
          <form action="{% url 'accounts:login' %}" method="POST">
              {% csrf_token %}
              <div class="form-group">
                 <input  required ="email" class="form-control" placeholder="Email Address" name="email" >
              </div> <!-- form-group// -->
              <div class="form-group">
                <input required type="password" class="form-control" placeholder="Password" name="password">
              </div> <!-- form-group// -->
              
              <div class="form-group">
                  <a href="{% url 'accounts:forgotPassword' %}" class="float-right">Forgot password?</a> 
               
              </div> <!-- form-group form-check .// -->
              <div class="form-group">
                  <button type="submit" class="btn btn-primary btn-block"> Login  </button>
              </div> <!-- form-group// -->    
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
         <p class="text-center mt-4 ">Don't have account? <a  href="{% url 'accounts:register' %}">Sign up</a></p>
         <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    {% endif %}
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/register.html
{% extends 'layouts/base.html' %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">

    <!-- ============================ COMPONENT REGISTER   ================================= -->
        <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
          <article class="card-body">
              {% include 'includes/alerts.html' %}
            <header class="mb-4"><h4 class="card-title">Sign up</h4></header>
            <form action="{% url 'accounts:register' %}" method="POST">
                {% csrf_token %}
            
                <div class="form-row">
                    <div class="col-6 form-group">
                        <label>First name</label>
                        {{ form.first_name }}
                        {{ form.first_name.errors }}
                    </div>
                    <div class="col-6 form-group">
                        <label>Last name</label>
                        {{ form.last_name }}
                        {{ form.last_name.errors }}
                    </div>
                </div>
            
                <div class="form-row">
                    <div class="col-6 form-group">
                        <label>Email</label>
                        {{ form.email }}
                        {{ form.email.errors }}
                    </div>
                    <div class="form-group col-md-6">
                        <label>Phone Number</label>
                        {{ form.phone_number }}
                        {{ form.phone_number.errors }}
                    </div>
                </div>
            
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Create password</label>
                        {{ form.password }}
                        {{ form.password.errors }}
                    </div>
                    <div class="form-group col-md-6">
                        <label>Repeat password</label>
                        {{ form.confirm_password }}
                        {{ form.confirm_password.errors }}
                    </div>
                </div>
            
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Register</button>
                </div>
            
                {{ form.non_field_errors }}
            </form>
            
            </article><!-- card-body.// -->
        </div> <!-- card .// -->
        <p class="text-center mt-4">Have an account? <a href="{% url 'accounts:login' %}">Log In</a></p>
        <br><br>
    <!-- ============================ COMPONENT REGISTER  END.// ================================= -->
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/reset_password_email.html
{% autoescape off %}
Hi {{user.first_name}},
Please click link below to reset your password at Fantasy Team.
http://{{domain}}{% url 'accounts:resetpassword_validate' uidb64=uid token=token %}

If you think this is not you. Please ignore this email.
{% endautoescape %}