accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('register/', views.RegistrationView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('activate/<uidb64>/<token>/', views.ActivateView.as_view(), name='activate'),
    path('forgotPassword/', views.ForgotPasswordView.as_view(), name='forgotPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', views.ResetPasswordValidateView.as_view(), name='resetpassword_validate'),
    path('resetPassword/', views.ResetPasswordView.as_view(), name='resetPassword'),

    path('profile/', views.EditProfileView.as_view(), name='edit_profile'),
    path('change_password/', views.ChangePasswordView.as_view(), name='change_password'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('accounts.urls')),
    path("fantasy/", include('fantasy.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fantasy/urls.py
from django.urls import path
from .views import *

app_name = 'fantasy'

urlpatterns = [
    path('sync-match-points/', SyncMatchPointsView.as_view(), name='sync-match-points'),
    path('my-team/<int:pk>/points', MyTeamView.as_view(), name='my-team-overall'),
    path('leaderboard/', LeaderBoard.as_view(), name='overall-leaderboard'),
    path('fantasy/<int:pk>/article/', ArticleDetailView.as_view(), name='article-detail'),
    path('create/my-team/', CreateFantasyTeam.as_view(), name='create-team'),
]

templates/includes/alerts.html
{% if messages or success_msg %}
    <style>
        .notification__wrapper {
            position: fixed;
            top: 70px;
            right: 30px;
            z-index: 11111;
        }

        .notification__wrapper ul {
            margin: 0;
            padding: 0;
            list-style: none;
            display: flex;
            flex-direction: column;
            gap: 10px;
        }

        .notification__box {
            display: flex;
            align-items: center;
            gap: 15px;
            padding: 20px;
            box-shadow: 0 0 10px rgba(0, 0, 0, .2);
            border-radius: 4px;
            max-width: 400px;
            width: 400px;
            position: relative;
            overflow: hidden;
            opacity: 0;
            transform: translateX(120%);
            transition: all .3s ease-in-out;
            background-color: #fff;
            z-index: 11111;
        }

        .notification__box.active {
            opacity: 1;
            transform: translateX(0%);
        }

        .notification__icon img {
            width: 25px;
            height: auto;
        }

        .notification__para {
            margin-bottom: 0px;
            color: #0C0B04;
            font-size: 15px;
            font-weight: 400;
            line-height: 1.3;
            margin-right: 20px;
        }

        .notification__green {
            background-color: #EBFBF6;
        }

        .notification__red {
            background-color: #FDEDEE;
        }

        .notification__yellow {
            background-color: #FFF9E9;
        }

        .notification__blue {
            background-color: #E6FAFD;
        }

        .notification__close {
            position: absolute;
            top: 50%;
            transform: translateY(-50%);
            right: 20px;
            font-size: 15px;
            font-weight: 500;
            display: flex;
            color: #ccc;
            transition: all .2s ease-in-out;
            cursor: pointer;
        }

        .notification__close:hover {
            color: #0C0B04;
        }

        .notification__green .notification__close:hover {
            color: #35D29D;
        }

        .notification__red .notification__close:hover {
            color: #F04D62;
        }

        .notification__yellow .notification__close:hover {
            color: #FFC12B;
        }

        .notification__blue .notification__close:hover {
            color: #01D0EA;
        }

        .notification__icon-rotate {
            transform: rotate(180deg);
        }

        .notification__progress {
            position: absolute;
            bottom: 0;
            left: 0;
            height: 4px;
            width: 100%;
        }

        .notification__progress:before {
            content: "";
            position: absolute;
            bottom: 0;
            right: 100%;
            height: 100%;
            width: 100%;
            background-color: #4070f4;
        }

        .notification__green .notification__progress:before {
            background-color: #35D29D;
        }

        .notification__red .notification__progress:before {
            background-color: #F04D62;
        }

        .notification__yellow .notification__progress:before {
            background-color: #FFC12B;
        }

        .notification__blue .notification__progress:before {
            background-color: #01D0EA;
        }


        .notification__progress.active:before {
            animation: progress 4s linear forwards;
        }

        @keyframes progress {
            0% {
                right: 0;
            }

            100% {
                right: 100%;
            }
        }
    </style>
    <!--notification-wrapper-->


<body class="menubar-hoverable header-fixed menubar-pin ">
    <div class="notification__wrapper">
        <ul>
            {% if success_msg %}
            <li>
                <!--successfully-done-something---use-for-positive-notification-->
                <div class="notification__box notification__green">
                    <div class="notification__icon">
                        <img src="https://nepalbahas.prixacdn.net/media/albums/notification_check_S5J5pJ57J4.png" alt="">
                    </div>
                    <p class="notification__para">{{ success_msg }}</p>
                    <a class="notification__close"><i class="fa fa-times" aria-hidden="true"></i></a>
                    <div class="notification__progress"></div>
                </div>
                <!--end-->
            </li>
            {% endif %}
            {% for message in messages %}
            {% if message.tags == 'success' %}
            <li >
                <div class="notification__box notification__green">
                    <div class="notification__icon">
                        <img src="https://nepalbahas.prixacdn.net/media/albums/notification_check_S5J5pJ57J4.png" alt="">
                    </div>
                    <p class="notification__para">{{message}}</p>
                    <a class="notification__close"><i class="fa fa-times" aria-hidden="true"></i></a>
                    <div class="notification__progress"></div>
                </div>
            </li>
            {% elif message.tags == 'error' %}
            <li >
                <!--error-notification-and-other-related-stuff-->
                <div class="notification__box notification__red">
                    <div class="notification__icon notification__icon-rotate">
                        <img src="https://nepalbahas.prixacdn.net/media/albums/notification_red_dqstw3rfgP.png" alt="">
                    </div>
                    <p class="notification__para">{{message}}</p>
                    <a class="notification__close"><i class="fa fa-times" aria-hidden="true"></i></a>
                    <div class="notification__progress"></div>
                </div>
                <!--end-->
            </li>
            {% elif message.tags == 'warning' %}
            <li >
                <!--warning-notification-and-other-related-stuff-->
                <div class="notification__box notification__yellow">
                    <div class="notification__icon notification__icon-rotate">
                        <img src="https://nepalbahas.prixacdn.net/media/albums/notification_yellow_P60qALiJoc.png" alt="">
                    </div>
                    <p class="notification__para">{{message}}</p>
                    <a class="notification__close"><i class="fa fa-times" aria-hidden="true"></i></a>
                    <div class="notification__progress"></div>
                </div>
                <!--end-->
            </li>
            {% elif message.tags == 'info' %}
            <li >
                <!--normal-notification-and-other-related-stuff-->
                <div class="notification__box notification__blue">
                    <div class="notification__icon ">
                        <img src="https://nepalbahas.prixacdn.net/media/albums/notification_blue_WbeFThl7zG.png" alt="">
                    </div>
                    <p class="notification__para">{{message}}</p>
                    <a class="notification__close"><i class="fa fa-times" aria-hidden="true"></i></a>
                    <div class="notification__progress"></div>
                </div>
                <!--end-->
            </li>
            {% endif %}
            {% endfor %}
        </ul>
    </div>
    <script src="https://unpkg.com/phosphor-icons"></script>

    <script>
        $(document).ready(function () {
            $('.notification__box').addClass('active');
            $('.notification__progress').addClass('active');
            var notificationBox = $('.notification__box');
            setTimeout(() => {
                $('.notification__box').removeClass('active');
                $('.notification__progress').removeClass('active');
            }, 4000);
        });
    </script>
    <script>
        $('.notification__close').click(function () {
            $(this).parent('.notification__box').removeClass('active');
        });
    </script>

</body>

</html>

{% endif %}

templates/includes/footer.html
    <!-- Footer -->
    <footer class="bg-light text-dark pt-4 my-3">
        <div class="container text-center text-md-left">
            <div class="row text-center text-md-left">
                <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
                    <h5 class="mb-4 font-weight-bold">Fantasy League</h5>
                    <p>Join our fantasy football community and experience the thrill of the game!</p>
                </div>

                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
                    <h5 class="mb-4 font-weight-bold">Links</h5>
                    <p><a href="{% url 'accounts:about' %}" class="text-dark">About</a></p>
                    <p><a class="text-dark" href="{% if request.user.is_authenticated %}{% if not request.user.fantasyteam.first %}{% url 'fantasy:create-team' %}{% else %}{% url 'fantasy:my-team-overall' request.user.fantasyteam.first.pk %}{% endif %}{% else %}{% url 'accounts:login' %}{% endif %}">My Team</a></p>
                    <p><a class="text-dark" href="{% url 'fantasy:overall-leaderboard' %}">Leaderboard</a></p>
                    
                
                </div>

                <!-- Add more columns as needed -->
            </div>

            <hr class="mb-4">

            <div class="row align-items-center">
                <div class="col-md-7 col-lg-8">
                    <p>&copy; 2023 Fantasy League. All rights reserved.</p>
                </div>

                <div class="col-md-5 col-lg-4">
                    <div class="text-center text-md-right">
                        <ul class="list-unstyled list-inline">
                            <li class="list-inline-item"><a href="#" class="btn-floating btn-sm text-dark"><i class="fab fa-facebook-f"></i></a></li>
                            <li class="list-inline-item"><a href="#" class="btn-floating btn-sm text-dark"><i class="fab fa-twitter"></i></a></li>
                            <li class="list-inline-item"><a href="#" class="btn-floating btn-sm text-dark"><i class="fab fa-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{% url 'accounts:home' %}"><strong>Fantasy League</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
                <a class="nav-item nav-link active" href="{% url 'accounts:home' %}">Home <span class="sr-only">(current)</span></a>
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'accounts:edit_profile' %}">Profile</a>
                {% endif %}
                
                <a class="nav-item nav-link" href="{% if request.user.is_authenticated %}{% if not request.user.fantasyteam.first %}{% url 'fantasy:create-team' %}{% else %}{% url 'fantasy:my-team-overall' request.user.fantasyteam.first.pk %}{% endif %}{% else %}{% url 'accounts:login' %}{% endif %}">My Team</a>
                <a class="nav-item nav-link" href="{% url 'fantasy:overall-leaderboard' %}">Leaderboard</a>
                <a class="nav-item nav-link" href="{% url 'accounts:about' %}">About</a>
            
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">
                        <i class="fa fa-sign-out" aria-hidden="true"></i> Logout
                    </a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'accounts:login' %}">
                        <i class="fa fa-sign-in" aria-hidden="true"></i> Login
                    </a>
                {% endif %}
            </div>
            
        </div>
        
    </div>
</nav>